blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/brainxio/github-flow-agency/discussions
    about: Please ask questions, share ideas, or start general conversations here.
